stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry-infra-gitlab.otr.ru:5005
    - docker build -t registry-infra-gitlab.otr.ru:5005/eb-admins/py_ufos_autotest .
    - docker push registry-infra-gitlab.otr.ru:5005/eb-admins/py_ufos_autotest:latest
#  only:
#    - docker


run_container:
  stage: deploy
  script:
    - docker container rm -f py_ufos_autotest
    - docker container run -d --restart on-failure --name py_ufos_autotest registry-infra-gitlab.otr.ru:5005/eb-admins/py_ufos_autotest:latest
#  only:
#    - docker