#image: ufos_autotest:latest
image: infra-gitlab.otr.ru/eb-admins/py_autotest_image:latest

test:
  script: 
#     - systemctl stop firewalld
#     - systemctl disable firewalld
     - echo $UFOS_USER
     - echo $UFOS_PASSWORD
     - echo $UFOS_SERVER
     - cd /builds/eb-admins/py_ufos_autotest/
     - chmod +x chromedriver
     - chmod +x zabbix_sender
     - python3 ufos_autotest.py -l $UFOS_USER -p $UFOS_PASSWORD -u $UFOS_SERVER
#     - yum install -y iputils
#     - ping vs-c06-zabbix_proxy02.pds.otr.ru
#'-c', '--config', help='Input Config file name', default='config.json'
#'-u', '--url', help='Input a stand URL with a port. Example http://stand-test.otr.ru:8889'
#'-l', '--login', help='Input a Login'
#'-p', '--password', help='Input a Password'

