stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry-gitlab:5005
    - docker build -t registry-gitlab:5005/admins/py_ufos_autotest .
    - docker push registry-gitlab:5005/admins/py_ufos_autotest:latest
#  only:
#    - docker


run_container:
  stage: deploy
  script:
    - docker container rm -f py_ufos_autotest
    - docker container run -d --restart on-failure --name py_ufos_autotest registry-gitlab:5005/admins/py_ufos_autotest:latest
#  only:
#    - docker
